# Generated by Django 2.1.5 on 2019-03-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchcollection',
            name='merch',
            field=models.ForeignKey(default='mrah', on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='merch.Merch'),
            preserve_default=False,
        ),
    ]
