# Generated by Django 2.1.5 on 2019-03-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_auto_20190304_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchcollection',
            name='description',
            field=models.CharField(default='T-shirt', max_length=4096),
            preserve_default=False,
        ),
    ]
