# Generated by Django 2.1.5 on 2019-03-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merchcollection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchcollection',
            name='description',
        ),
    ]
