# Generated by Django 2.1.5 on 2019-03-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_remove_merchcollection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='collection',
        ),
        migrations.DeleteModel(
            name='MerchCollection',
        ),
    ]
