# Generated by Django 2.1.5 on 2019-03-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_auto_20190304_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='merch_image',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='slug',
        ),
    ]
