# Generated by Django 2.1.5 on 2019-01-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
    ]
