# Generated by Django 2.1.5 on 2019-01-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productvariant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='mrah', max_length=128),
            preserve_default=False,
        ),
    ]
