# Generated by Django 2.1.5 on 2019-01-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('total_fat', models.IntegerField(default=0)),
                ('saturated_fat', models.IntegerField(default=0)),
                ('trans_fat', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
                ('total_carbohydrate', models.IntegerField(default=0)),
                ('total_sugars', models.IntegerField(default=0)),
                ('added_sugars', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default='mrah', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='products.Product'),
        ),
    ]
