# Generated by Django 2.1.5 on 2019-01-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190123_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionFacts',
            new_name='NutritionFact',
        ),
    ]
