# Generated by Django 2.1.5 on 2019-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190123_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(default='mrah', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='products.Product'),
        ),
    ]
