# Generated by Django 2.1.5 on 2019-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190123_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='products',
            new_name='product',
        ),
    ]
