# Generated by Django 2.1.5 on 2019-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190123_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='order_by',
            field=models.IntegerField(default=99),
        ),
    ]
